name: Run Selenium Tests on Push

on:
  push:
    branches:
      - main  # Change if you're using another branch (e.g., "master" or "dev")

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'  # Change if you're using a different version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Pytest tests
        run: |
          pytest tests/ --disable-warnings --maxfail=5
