name: Run Selenium Tests on Push

on:
  push:
    branches:
      - main  # Change if you're using another branch (e.g., "master" or "dev")

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest-html

      - name: Run Pytest tests and generate HTML report
        run: |
          pytest tests/ --disable-warnings --maxfail=5 --html=report.html

      - name: Upload HTML report as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pytest-html-report
          path: report.html

