name: Run Selenium Tests on Push

on:
  push:
    branches:
      - main
  schedule:
    - cron: '*/5 * * * *'

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.2'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --upgrade pytest-html


      - name: Run Pytest tests in parallel and generate HTML report
        run: |
          mkdir -p tests/Screenshots
          pytest tests/ -v -s \
            --disable-warnings \
            --maxfail=5 \
            --reruns 2 \
            -n auto \
            --html=report.html \
            --self-contained-html

      - name: Upload HTML report as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-html-report
          path: report.html

